services:
  - type: web
    name: ml-api
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn mlapi.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000  # Required for Render's internal routing
      - key: PYTHON_VERSION
        value: 3.11.6  # Match your local Python version
      - key: DJANGO_SETTINGS_MODULE
        value: mlapi.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "ml-api.onrender.com *.onrender.com"  # Wildcard for all Render URLs
      - key: DISABLE_COLLECTSTATIC
        value: 0  # Only if using Whitenoise
    database:
      name: mlapi-mysql
      plan: free  # Or your chosen plan
    plan: starter
    healthCheckPath: /health/
    autoDeploy: true